export const ADD_POKE_SUCCESS = 'ADD_POKE_SUCCESS';
export const ADD_POKE_FAILED = 'ADD_POKE_FAILED';

export const RELEASE_POKE_SUCCESS = 'RELEASE_POKE_SUCCESS'
export const RELEASE_POKE_FAILED = 'RELEASE_POKE_FAILED'